---
ID: "5d60e6dc-6aa3-48db-a89b-c046ec48b5ba"
Parent: "d1464a9c-3663-4bf7-9907-5dd0e2820d39"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Estimation Form/Page/Section/Section(5)/Section(13)/Product size/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200824T052144Z
